commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace='store')),
    path("", include("user.urls", namespace='user')),
    path("", include("purchase.urls", namespace="purchase")),
    # path("", include("store.urls", namespace="store")),
]
# append a media url to urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.urls import path
from store import views

app_name = "purchase"
urlpatterns = [
    # path("", views.store, name="list"),
    # path("cart/", views.cart, name="cart"),
    # path("checkout/", views.checkout, name="checkout"),
    # path("logout/", UserLogoutView.as_view(), name="logout"),
    # path("profile/", UserProfileView.as_view(), name="profile"),
]

store/urls.py
from django.urls import path
from store import views

app_name = "store"
urlpatterns = [
    path("", views.store, name="list"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    # path("logout/", UserLogoutView.as_view(), name="logout"),
    # path("profile/", UserProfileView.as_view(), name="profile"),
]

user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from user.views import UserLoginView, UserRegisterView

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

purchase/models.py
from django.db import models

from store.models import Product
from user.models import Customer


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse_lazy
from django.utils.text import slugify

from django.utils.translation import gettext as _


class Product(models.Model):
    """Product model implementation"""

    class Meta:
        db_table = "product"
        verbose_name = _("product")
        verbose_name_plural = _("products")

    brand = models.CharField(
        max_length=128,
        verbose_name=_("product brand title"),
        help_text=_("Required. 128 characters or fewer."),
    )

    product = models.CharField(
        max_length=128,
        verbose_name=_("product title"),
        help_text=_("Required. 128 characters or fewer."),
    )

    slug = models.SlugField(
        max_length=128,
        verbose_name=_("product slug"),
        help_text=_("Required. 128 characters or fewer. "
                    "Letters, numbers, hyphens and underscores."),
    )

    image = models.ImageField(
        upload_to="product",
        default="default/product.png",
    )

    description = models.TextField(
        verbose_name=_("product description and/or specifications"),
        help_text=_("Required")
    )

    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
        validators=[MinValueValidator(0.00)],
        verbose_name=_("price for a single item"),
        help_text=_("A positive decimal number. Defaults to numeric zero."),
    )

    quantity = models.IntegerField(
        default=0,
        validators=[MinValueValidator(0)],
        verbose_name=_("number of available items"),
        help_text=_("A positive integer number. Defaults to integer zero."),
    )

    def __repr__(self):
        """Return a string representation of an instance"""

        return f"<{self.__class__.__name__} pk={self.pk} ('{self}')>"

    def __str__(self):
        """Return a string version of an instance"""

        return self.product

    @property
    def name(self):
        """An alias to a product field"""

        return self.product

    def get_absolute_url(self):
        """Return an absolute URL to a product instance"""

        return reverse_lazy("store:detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        """Override save method"""

        if not self.slug:
            self.slug = slugify(self.product)

        super(Product, self).save(*args, **kwargs)

user/models.py
from django.contrib.auth.models import User
from django.db import models


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from user.models import Customer


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]

purchase/views.py
from django.shortcuts import render

# Create your views here.

store/views.py
from django.shortcuts import render


def store(request):
    context = {}
    return render(request, 'store/store.html', context)


def cart(request):
    return render(request, 'store/cart.html')


def checkout(request):
    return render(request, 'store/checkout.html')

user/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from user.forms import UserRegisterForm


class UserRegisterView(CreateView):
    """User sign-up view implementation"""

    form_class = UserRegisterForm
    template_name = "user/register.html"
    success_url = reverse_lazy("user:login")


class UserLoginView(LoginView):
    """User sign-in view implementation"""

    template_name = "user/login.html"


class UserLogoutView(LogoutView):
    """User logout view implementation"""

    pass

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>My SHOP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<header>
  {% block navbar %}
    {% include "navbar.html" %}
  {% endblock %}
</header>
<div class="container">
    <br>
    {% block content %}
    {% endblock content %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'store:list' %}">Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'store:list' %}">Store <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% if request.user.is_authenticated %}
        <div class="form-inline my-2 my-lg-0">
            <a href="{% url "user:logout" %}" class="btn btn-danger">Logout</a>
            <a href="{% url "store:cart" %}"><img id="cart-icon" src="{% static 'images/cart.png' %}"></a>
            <p id="cart-total">0</p>
        </div>
        {% else %}
           <div class="d-grid gap-2">
            <a href="{% url "user:login" %}" class="btn btn-success">Login</a>
            <a href="{% url "user:register" %}" class="btn btn-success">Register</a>
        </div>
        {% endif %}
    </div>
</nav>

templates/store/cart.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:list' %}">&#x2190; Continue Shopping</a>
                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>3</strong></h5></th>
                        <th><h5>Total:<strong> $42</strong></h5></th>
                        <th>
{#                            <a style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>#}
                        </th>
                    </tr>
                </table>
            </div>
            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
                    <div style="flex:2"><p>Product 1</p></div>
                    <div style="flex:1"><p>$20</p></div>
                    <div style="flex:1">
                        <p class="quantity">2</p>
                        <div class="quantity">
                            <img class="chg-quantity" src="{% static  'images/arrow-up.png' %}">
                            <img class="chg-quantity" src="{% static  'images/arrow-down.png' %}">
                        </div>
                    </div>
                    <div style="flex:1"><p>$32</p></div>
                </div>

            </div>
        </div>
    </div>
{% endblock content %}

templates/store/checkout.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Name..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="Email..">
                        </div>
                    </div>

                    <div id="shipping-info">
                        <hr>
                        <p>Shipping Information:</p>
                        <hr>
                        <div class="form-field">
                            <input class="form-control" type="text" name="address" placeholder="Address..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="city" placeholder="City..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="state" placeholder="State..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="country" placeholder="Zip code..">
                        </div>
                    </div>

                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
                </form>
            </div>

            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
            </div>

        </div>

        <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
                    <div style="flex:2"><p>Product 1</p></div>
                    <div style="flex:1"><p>$20.00</p></div>
                    <div style="flex:1"><p>x2</p></div>
                </div>
                <h5>Items: 2</h5>
                <h5>Total: $4</h5>
            </div>
        </div>
    </div>
{% endblock content %}

templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>My SHOP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/store/store.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-4">
            <img class="thumbnail" src="{% static 'images/placeholder.png' %}">
            <div class="box-element product">
                <h6><strong>Product</strong></h6>
                <hr>
                <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
                <a class="btn btn-outline-success" href="#">View</a>
                <h4 style="display: inline-block; float: right"><strong>$20</strong></h4>
            </div>
        </div>
        <div class="col-lg-4">
            <img class="thumbnail" src="{% static 'images/placeholder.png' %}">
            <div class="box-element product">
                <h6><strong>Product</strong></h6>
                <hr>
                <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
                <a class="btn btn-outline-success" href="#">View</a>
                <h4 style="display: inline-block; float: right"><strong>$20</strong></h4>
            </div>
        </div>
        <div class="col-lg-4">
            <img class="thumbnail" src="{% static 'images/placeholder.png' %}">
            <div class="box-element product">
                <h6><strong>Product</strong></h6>
                <hr>
                <button class="btn btn-outline-secondary add-btn">Add to Cart</button>
                <a class="btn btn-outline-success" href="#">View</a>
                <h4 style="display: inline-block; float: right"><strong>$20</strong></h4>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user/login.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form autocomplete="off" method="post" class="row justify-content-center">
    <div class="col-6">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="mt-3">
        <button type="submit" class="btn btn-primary">Sign in</button>
        <a href="{% url "store:list" %}" class="btn btn-danger">Cancel</a>
      </div>
      <div class="mt-3">Have no an account? <a href="{% url "user:register" %}">Register</a></div>
    </div>
  </form>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form autocomplete="off" method="post" class="row justify-content-center">
    <div class="col-6">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="mt-3">
        <button type="submit" class="btn btn-primary">Register</button>
        <a href="{% url "store:list" %}" class="btn btn-danger">Cancel</a>
      </div>
      <div class="mt-3">Already have an account? <a href="{% url "user:login" %}">Sing In</a></div>
    </div>
  </form>
{% endblock %}